# Generated by Django 5.0.14 on 2026-04-23 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicians', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('visits_ordered', models.JSONField(blank=True, default=list)),
                ('solver_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_plans', to='clinicians.clinician')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_plans', to='tenancy.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='routeplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'clinician', 'date'), name='uniq_route_plan_per_tenant_clinician_date'),
        ),
    ]
