# Generated by Django 5.0.14 on 2026-04-25 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicians', '0002_clinicianposition'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAgencyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('visits_completed', models.IntegerField(default=0)),
                ('missed_count', models.IntegerField(default=0)),
                ('on_time_pct', models.FloatField(default=0.0)),
                ('sms_sent', models.IntegerField(default=0)),
                ('sms_delivered', models.IntegerField(default=0)),
                ('rolled_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_agency_stats', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DailyClinicianStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('visits_completed', models.IntegerField(default=0)),
                ('on_time_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('total_drive_seconds', models.IntegerField(default=0)),
                ('total_on_site_seconds', models.IntegerField(default=0)),
                ('rolled_at', models.DateTimeField(auto_now=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='clinicians.clinician')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_clinician_stats', to='tenancy.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dailyagencystats',
            constraint=models.UniqueConstraint(fields=('tenant', 'date'), name='uniq_daily_agency_stats_tenant_date'),
        ),
        migrations.AddIndex(
            model_name='dailyclinicianstats',
            index=models.Index(fields=['tenant', 'date'], name='reporting_d_tenant__077dd2_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyclinicianstats',
            constraint=models.UniqueConstraint(fields=('tenant', 'clinician', 'date'), name='uniq_daily_clinician_stats_tenant_clinician_date'),
        ),
    ]
