# Generated by Django 5.0.14 on 2026-04-23 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', models.CharField(choices=[('RN', 'Registered Nurse'), ('LVN', 'Licensed Vocational Nurse'), ('MA', 'Medical Assistant'), ('phlebotomist', 'Phlebotomist')], max_length=32)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('home_lat', models.FloatField()),
                ('home_lon', models.FloatField()),
                ('shift_windows', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinicians', to='tenancy.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinician_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
