# Generated by Django 5.0.14 on 2026-04-23 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicianPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('ts', models.DateTimeField()),
                ('heading', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='clinicians.clinician')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinician_positions', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['clinician', '-ts'], name='cpos_clinician_ts_desc')],
            },
        ),
    ]
